services:
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - redis
    environment:
      APP_USER: "There"

  redis:
    image: "redis:8"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
